# Generated by Django 4.1.5 on 2023-01-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadFornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('Fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadFornecedor.fornecedor')),
            ],
        ),
    ]
