# Generated by Django 4.1.5 on 2023-01-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadFornecedor', '0002_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='tipo',
            field=models.CharField(choices=[('s', 'Seco'), ('m', 'Molhado')], default='Faça uma escolha', max_length=1),
        ),
    ]
