# Generated by Django 4.1.5 on 2023-01-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadFornecedor', '0003_vendedor_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='tipo',
            field=models.CharField(choices=[('s', 'Seco'), ('m', 'Molhado')], default='Seco', max_length=1),
        ),
    ]
