# Generated by Django 4.1.5 on 2023-01-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadFornecedor', '0004_alter_vendedor_tipo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='Fornecedor',
            new_name='fornecedor',
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('s', 'Seco'), ('m', 'Molhado')], default='Seco', max_length=1)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadFornecedor.fornecedor')),
            ],
        ),
    ]
