# Generated by Django 4.1.5 on 2023-01-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadFornecedor', '0005_rename_fornecedor_vendedor_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='produto',
            name='marca_produto',
            field=models.CharField(default=0, max_length=100, verbose_name='Marca Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(default=0, max_length=100, verbose_name='Nome Produto'),
        ),
    ]
