# Generated by Django 4.1.5 on 2023-01-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadFornecedor', '0006_alter_fornecedor_options_alter_vendedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='marca_produto',
            field=models.CharField(max_length=100, verbose_name='Marca Produto'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome_produto',
            field=models.CharField(max_length=100, verbose_name='Nome Produto'),
        ),
    ]
