# Generated by Django 4.1.5 on 2023-02-01 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadFornecedor', '0008_alter_fornecedor_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome_lista', models.CharField(help_text='Compra dia XX/xx', max_length=100, verbose_name='Nome da Lista')),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total da Compra')),
            ],
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(help_text='00.000.000/0001-00', max_length=18, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(help_text='(62) 3333-3333', max_length=20),
        ),
        migrations.CreateModel(
            name='add_lista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qnt_produto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade do produto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lista_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lista', to='cadFornecedor.compra')),
                ('produto_nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lista', to='cadFornecedor.produto')),
            ],
        ),
    ]
