# Generated by Django 4.1.5 on 2023-02-01 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadFornecedor', '0009_compra_alter_fornecedor_cnpj_alter_fornecedor_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLista',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='compra',
            name='total_compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='valor_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nome_lista',
            field=models.CharField(max_length=100, verbose_name='Nome da Lista'),
        ),
        migrations.DeleteModel(
            name='add_lista',
        ),
        migrations.AddField(
            model_name='itemlista',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadFornecedor.compra'),
        ),
        migrations.AddField(
            model_name='itemlista',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadFornecedor.produto'),
        ),
    ]
