# Generated by Django 4.1.5 on 2023-01-29 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.TextField()),
                ('telefone', models.CharField(max_length=15)),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('qnt_marmita', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade de marmitas')),
                ('valor_marmita', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor und marmita')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadCliente.cliente')),
            ],
        ),
    ]
