# Generated by Django 4.1.5 on 2023-01-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadCliente', '0002_remove_pedido_debito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.CharField(choices=[('s', 'sim'), ('n', 'não')], default='n', max_length=1),
        ),
    ]
